task_model:
    class: pointnet2.models.PointTransformerClassification
    name: cls-pointtransformer
optimizer:
    lr: 0.001 
    momentum: 0.9
    weight_decay: 0.0001
    milestones: "120.160"
    gamma: 0.1
batch_size: 16
